### ISSUE TITLE
Systematic error in results?

### ISSUE THREAD

**Issue by jzrapp** [borenstein-lab/empanada#3]
Hi @engal and @omanor,

me again :) 
I observe some patterns in my results that I don't really trust and I was hoping to get some of your insights on the issue. I used musicc to normalize my datasets (two very different environments, one heavily impacted by the presence of viruses and eukaryota, and the other not). I removed the eukaryotic fraction to the best of my abilities. 
Following musicc, I used empanada to group my KO assignments to pathways. I saw your example data, which seems to be KO counts transformed to relative abundances..? But I'm assuming musicc normalized abundances should work as well, is that right? Or should they be transformed to relative abundances after musicc normalization?
What I'm seeing now is that basically all of the pathways are significantly higher in one environment vs the other (see attached quick and dirty plot). While some of them do make sense from an ecological perspective, I just cannot believe that the microbes of that one environment have higher average gene copy number per genome for all of these pathways.

So my questions are: Does my workflow seem reasonable to you or should I have used different input files?
And if it does seem right, do you think that there might be a bias in my data, e.g. introduced by the apparently much higher number of viral sequences in one environment vs the other (the environment where empanada pathways are lower). 150 gene copies of ABC transporter genes per genome seems like a lot!

Best,
Josephine

![example_data 001](https://user-images.githubusercontent.com/16957339/73038000-b9221a80-3e05-11ea-903f-305e912c7963.jpeg)

**Comment by engal** [comment]
Hi Josephine,

It would be helpful to know what settings you used for MUSiCC and empanada, though I can hopefully give you some useful information without that.

First, empanada should be fine using MUSiCC profiles. There is no need to turn those profiles into relative abundances, and I would in fact recommend not converting to relative abundances as the goal of MUSiCC is to transform the data into a more meaningful space.

I should also mention that the interpretation for pathway-level MUSiCC data is slightly different than normal MUSiCC data. At the pathway level, MUSiCC data instead represents the average number of genes belonging to a pathway per genome, rather than the copy number of an individual gene. For a simple example, if we're only considering a single pathway A that contains genes B, C, and D, and the average copy number of genes B, C, and D are each 1 in a given sample, then the empanada-calculated value for pathway A for that sample should be 3 (for default empanada settings). Similarly, if another sample has an average copy number of 1 for genes B and C, but an average copy number of 0 for gene D, then the empanada-calculated value for pathway A will be 2 (again for default empanada settings).

What this means, possibly in relation to your results, is that if organisms in one sample tend to have more genes belonging to a pathway, that pathway will appear at a higher abundance. This might occur somewhat systematically, for example, if organisms with larger genomes are more abundant in one environment compared to another. Getting back to your data in particular, I'm not sure how you mapped your sequencing data to genes, but if the viral sequences are contributing to the gene abundances and they are more abundant in one environment, then that may also explain why you see a systematic increase in pathway abundances. MUSiCC corrects gene abundances based on the assumption that bacterial genomes share a collection of universal single copy genes, but if viral sources of KO-annotated genes are a large component of your sample, then this assumption may be violated. Viral genes would inflate MUSiCC-corrected abundances because MUSiCC is specifically calculating the average copy number of each gene per **bacterial** genome, and the viral genes may be effectively acting as additional genomic content without increasing the apparent number of bacterial genomes (i.e. inflating the apparent size of bacterial genomes in the sample). I'm not sure exactly what you are looking for, but it is important to keep this in mind when interpreting your results.

Regarding your current workflow, if you are not already, I would suggest using the "-map by_support" option for empanada, which should help a bit in terms of giving you more meaningful results. Briefly, when you use this setting, empanada assigns gene abundance to pathways such that all genes belonging to the pathway contribute a similar abundance to the pathway. You can find a more in-depth explanation in the associated paper: Revised computational metagenomic processing uncovers hidden and biologically meaningful functional variation in the human microbiome, Manor and Borenstein, 2017. This may be more biologically meaningful than the default "naive" mapping method.

For the example you pointed out, 150 average copies per genome for ABC transporters, I think this number is probably reasonable (assuming you were using default settings) due to the large number of genes associated with the ABC transporter pathway classification. If you want a different interpretation of abundance (which I think might be what you were expecting based on your comment), you can use the "-map by_avg_abundance" setting for empanada, which will calculate the abundance of each pathway based on the average abundance of genes belonging to the pathway, rather than the sum of their abundances (which is the default "naive" setting). This won't change the differences you see between your environments, but the values you get will have a different interpretation that might be closer to your expectation.

Hope that helps (and isn't too confusing). I may have additional comments depending on exactly which settings you were using for MUSiCC and empanada.

**Comment by jzrapp** [comment]
Hi Alex, 

first of all I want to say that I'm extremely thankful for your very detailed reply! It has been very helpful! 
I took some time to try the different settings and compare results. I apologize for not providing more info on my settings in the first place. 
Originally I had used these settings to run musicc and empananda: 

`
run_musicc.py data_for_musicc_allK0.txt -n -c learn_model -v -o ko_MUSiCC_Normalized_Corrected_learn_model_allKO.tab
`

```
Normalize: True
Correct: learn_model
Compute scores: False
Loading data using pandas module...
11 samples and 10601 genes
Done.
Performing MUSiCC Correction...
Learning sample-specific models
...........Done.
Performing MUSiCC Normalization...
median USiCG before MUSiCC = [ 8282.   7795.5  5046.5 29409.   7439.   7680.5 10906.5 15342.   8363.5 13129.  12246. ]
median USiCG after MUSiCC = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Done.
Done.
Running time was 2 seconds.
```
Followed by empanada with:

`
run_empanada.py -ko musicc_for_EMPANADA.txt -ko2path KOvsPATHWAY_BACTERIAL_KEGG_2013_07_15.txt --output EMPANADA_out.txt --output_counts EMPANADA_counts.txt --output_mapping EMPANADA_mapping.txt --mapping_method by_avg_abundance -use_only_non_overlapping_genes -remove_ko_with_no_abundance_measurement  -leave_one_ko_out_pathway_support -fraction -v
`

After you replied to me, I rerun empanada using: 

`run_empanada.py -ko musicc_for_EMPANADA.txt -ko2path KOvsPATHWAY_BACTERIAL_KEGG_2013_07_15.txt --output EMPANADA_out_test.txt --output_counts EMPANADA_counts_test.txt --output_mapping EMPANADA_mapping_test.txt --mapping_method by_support -use_only_non_overlapping_genes -v -remove_ko_with_no_abundance_measurement`

I think you are right, and the mapping by support seems to give a more reasonable picture of my data. Overall the trend is not so much leaning towards everything being more abundant in that one group, and I can see more variability between my two sample types.
Please let me know if you have further comments on the setting that I chose. 

Coming back to this trend of higher abundance in red vs blue: Based on genome reconstruction of several dominant community members in the two sample types, it doesn't seem like organisms in one sample type have markedly larger genome sizes.
Also, thanks for sharing your thoughts on the issue of viruses present in the data. I came to the same conclusion as you, but needed reassurance that my line of thought made sense. The interesting thing is that viral sequences seem to be more abundant in the blue environment (see plot above). The result seems to be contrary to what I would expect (if the viral sequences do indeed influence the results, I would have expected that this group should systematically have higher numbers). So I guess, the viral genes do add genomic content, but a large fraction of it is unknown and therefore without ko assignment.
By the way, did you document somewhere how you created the KOvsPATHWAY_BACTERIAL_KEGG_2013_07_15.txt file or where you retrieved it?

All the best,
Josephine

**Comment by engal** [comment]
Hi Josephine,

Sounds like things are working better now, glad I could help!

Regarding the KO-to-Pathway mapping file, that was generated from a snapshot of the KEGG database downloaded on 7/15/2013, before it became a subscription-based service (as such, we do not believe we can provide updated files derived directly from KEGG data files under the new license). Briefly, the KEGG database associates KOs with KEGG pathways, so this table reflects whether or not a KO was associated with the pathway (1 for yes, 0 for no). This table was then further filtered to only include "bacterial" pathways. In this case, we defined a pathway as "bacterial" if A) at least 1% of bacterial genomes in KEGG contained at least 1 KO from the pathway and B) those bacterial genomes contained at least 5% of the KOs in the pathway on average (following the methodology outlined in Manor et al., 2016, Metagenomic evidence for taxonomic dysbiosis and functional imbalance in the gastrointestinal tracts of children with cystic fibrosis).

Hope that helps!

Best,
Alex
